version: 2
updates:
  # Enable version updates for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/restapp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/jsp-spring"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
